import type { ToolbarItem } from "@/editor/toolbar/ToolbarItem";
import { buildThemeMenuItems } from "@/editor/toolbar/themeMenuItems";

/** 默认 AI 工具栏子项 id，与 {@link DEFAULT_TOOLBAR_ITEMS} 中 ai 菜单 children 同步。 */
export const AI_MENU_IDS = [
  "ai-polish",
  "ai-proofread",
  "ai-translate",
  "ai-summarize",
  "ai-custom",
] as const;

export const DEFAULT_TOOLBAR_ITEMS: ToolbarItem[] = [
  {
    id: "textFormat",
    type: "menu",
    label: "格式",
    title: "行内格式",
    children: [
      { id: "bold", label: "加粗", title: "加粗" },
      { id: "italic", label: "斜体", title: "斜体" },
      { id: "strikethrough", label: "删除线", title: "删除线" },
      { id: "code", label: "行内代码", title: "行内代码" },
      { id: "formatSep1", type: "separator" },
      {
        id: "highlightMenu",
        type: "menu",
        label: "高亮",
        title: "高亮颜色选择",
        children: [
          { id: "highlight", label: "默认", title: "==默认==" },
          {
            id: "highlightNote",
            label: "说明 (Note)",
            title: "==说明=={.note}",
          },
          { id: "highlightTip", label: "提示 (Tip)", title: "==提示=={.tip}" },
          {
            id: "highlightImportant",
            label: "重要 (Important)",
            title: "==重要=={.important}",
          },
          {
            id: "highlightWarning",
            label: "警告 (Warning)",
            title: "==警告=={.warning}",
          },
          {
            id: "highlightCaution",
            label: "谨慎 (Caution)",
            title: "==谨慎=={.caution}",
          },
          {
            id: "highlightDanger",
            label: "危险 (Danger)",
            title: "==危险=={.danger}",
          },
        ],
      },
      { id: "spoiler", label: "剧透", title: "!!剧透!!" },
      { id: "sup", label: "上标", title: "^上标^" },
      { id: "sub", label: "下标", title: "~下标~" },
      { id: "formatSep2", type: "separator" },
      {
        id: "comment",
        label: "行内注释",
        title: "%%注释%%（跨行按行拆分）",
      },
      { id: "math", label: "行内公式", title: "$行内公式$" },
      {
        id: "htmlAttr",
        label: "属性",
        title: "在选区后追加 {.class}",
      },
    ],
  },
  {
    id: "structure",
    type: "menu",
    label: "结构",
    title: "标题 / 列表 / 块级语法",
    children: [
      {
        id: "heading",
        type: "menu",
        label: "标题",
        title: "ATX 标题",
        children: [
          { id: "heading1", label: "一级标题" },
          { id: "heading2", label: "二级标题" },
          { id: "heading3", label: "三级标题" },
          { id: "heading4", label: "四级标题" },
          { id: "heading5", label: "五级标题" },
          { id: "heading6", label: "六级标题" },
        ],
      },
      { id: "unorderedList", label: "无序列表" },
      { id: "orderedList", label: "有序列表" },
      {
        id: "taskListMenu",
        type: "menu",
        label: "任务列表",
        children: [
          { id: "taskList", label: "待办" },
          { id: "taskInProgress", label: "进行中" },
          { id: "taskDeferred", label: "延期" },
          { id: "taskEarly", label: "提前" },
          { id: "taskCancelled", label: "取消" },
          { id: "taskUrgent", label: "紧急" },
          { id: "taskDone", label: "已完成" },
        ],
      },
      { id: "blockquote", label: "引用" },
      { id: "structureSep1", type: "separator" },
      {
        id: "codeBlockMenu",
        type: "menu",
        label: "代码块",
        children: [
          { id: "codeBlockBasic", label: "基础围栏" },
          { id: "codeBlockTitle", label: "带文件名" },
          { id: "codeBlockHighlight", label: "行号高亮" },
          { id: "codeBlockCollapse", label: "折叠长代码" },
        ],
      },
      { id: "mathBlock", label: "块级公式" },
      { id: "commentBlock", label: "块级注释" },
      { id: "horizontalRule", label: "分隔线" },
      { id: "structureSep2", type: "separator" },
      {
        id: "frontmatterMenu",
        type: "menu",
        label: "文档头",
        title: "YAML Frontmatter / 变量引用",
        children: [
          {
            id: "frontmatter",
            label: "YAML 文档头",
            title: "---\\ntitle: ...\\n---",
          },
          {
            id: "frontmatterVar",
            label: "变量引用",
            title: "[[变量名]]",
          },
        ],
      },
    ],
  },
  {
    id: "insert",
    type: "menu",
    label: "插入",
    title: "链接 / 媒体 / 图表",
    children: [
      { id: "link", label: "链接" },
      {
        id: "linkRefMenu",
        type: "menu",
        label: "链接引用",
        children: [
          {
            id: "linkReference",
            label: "引用式链接",
            title: "[文本][标识]",
          },
          {
            id: "linkRefDef",
            label: "链接引用定义",
            title: "[标识]: url",
          },
        ],
      },
      { id: "image", label: "图片" },
      { id: "table", label: "表格" },
      {
        id: "media",
        type: "menu",
        label: "媒体",
        children: [
          { id: "video", label: "视频" },
          { id: "audio", label: "音频" },
          { id: "iframe", label: "嵌入页" },
        ],
      },
      { id: "insertSep1", type: "separator" },
      {
        id: "mermaid",
        label: "Mermaid",
        title: "插入 Mermaid 图表",
      },
      {
        id: "echarts",
        label: "ECharts",
        title: "插入 ECharts 图表",
      },
      { id: "insertSep2", type: "separator" },
      { id: "emoji", label: "Emoji" },
      { id: "badge", label: "徽章" },
      {
        id: "footnoteMenu",
        type: "menu",
        label: "脚注",
        children: [
          { id: "footnoteRef", label: "插入引用" },
          { id: "footnoteDef", label: "插入定义" },
          { id: "footnoteBoth", label: "引用 + 定义" },
        ],
      },
    ],
  },
  {
    id: "components",
    type: "menu",
    label: "组件",
    title: "扩展 UI 区块",
    mobileOverflow: true,
    children: [
      {
        id: "alertMenu",
        type: "menu",
        label: "GitHub 告警",
        children: [
          { id: "alertNote", label: "说明" },
          { id: "alertTip", label: "提示" },
          { id: "alertImportant", label: "重要" },
          { id: "alertWarning", label: "警告" },
          { id: "alertCaution", label: "谨慎" },
        ],
      },
      {
        id: "containerMenu",
        type: "menu",
        label: "自定义容器",
        children: [
          { id: "containerTip", label: "提示" },
          { id: "containerWarning", label: "警告" },
          { id: "containerNote", label: "说明" },
          { id: "containerInfo", label: "信息" },
          { id: "containerImportant", label: "重要" },
          { id: "containerCaution", label: "谨慎" },
          { id: "containerDanger", label: "危险" },
          { id: "containerSep1", type: "separator" },
          { id: "containerCenter", label: "居中" },
          { id: "containerLeft", label: "左对齐" },
          { id: "containerRight", label: "右对齐" },
          { id: "containerJustify", label: "两端对齐" },
        ],
      },
      {
        id: "cards",
        type: "menu",
        label: "卡片",
        children: [
          { id: "card", label: "基础卡片" },
          { id: "linkCard", label: "链接卡片" },
          { id: "imageCard", label: "图片卡片" },
          { id: "repoCard", label: "仓库卡片" },
          { id: "cardGrid", label: "卡片网格" },
          { id: "cardMasonry", label: "瀑布流" },
        ],
      },
      { id: "componentsSep1", type: "separator" },
      { id: "tabs", label: "选项卡" },
      { id: "steps", label: "步骤条" },
      {
        id: "timelineMenu",
        type: "menu",
        label: "时间线",
        children: [
          { id: "timelineContainer", label: "插入时间线容器" },
          { id: "timelineNode", label: "插入时间节点" },
        ],
      },
      {
        id: "collapseMenu",
        type: "menu",
        label: "折叠面板",
        children: [
          { id: "collapseDefault", label: "手风琴（默认折叠）" },
          { id: "collapseExpanded", label: "手风琴（默认展开）" },
          {
            id: "collapseExpand",
            label: "多面板展开",
            title: "::: collapse expand",
          },
        ],
      },
      { id: "componentsSep2", type: "separator" },
      {
        id: "fields",
        type: "menu",
        label: "字段",
        children: [
          { id: "field", label: "单个字段" },
          { id: "fieldGroup", label: "字段组" },
        ],
      },
    ],
  },
  {
    id: "ai",
    type: "menu",
    label: "AI",
    title: "AI 助手",
    children: [
      { id: "ai-polish", label: "智能润色", title: "智能润色" },
      { id: "ai-proofread", label: "纠错校对", title: "纠错校对" },
      { id: "ai-translate", label: "翻译文本", title: "翻译文本" },
      { id: "ai-summarize", label: "生成摘要", title: "生成摘要" },
      { id: "ai-custom", label: "自定义", title: "自定义" },
    ],
  },
  {
    id: "themeMenu",
    type: "menu",
    label: "主题",
    title: "切换渲染主题",
    mobileOverflow: true,
    children: buildThemeMenuItems(),
  },
];
