import {
  ICON_ALERT,
  ICON_AUDIO,
  ICON_BADGE,
  ICON_BLOCKS,
  ICON_BOLD,
  ICON_CARD,
  ICON_COLLAPSE,
  ICON_CONTAINER,
  ICON_ECHARTS,
  ICON_EMOJI,
  ICON_EXT,
  ICON_FIELD,
  ICON_FOOTNOTE,
  ICON_FRONTMATTER,
  ICON_GRID,
  ICON_HEADING,
  ICON_HR,
  ICON_IFRAME,
  ICON_IMAGE,
  ICON_LINK,
  ICON_LIST,
  ICON_MATH,
  ICON_MERMAID,
  ICON_OLIST,
  ICON_PLUS,
  ICON_QUOTE,
  ICON_REPO,
  ICON_STEPS,
  ICON_STRUCTURE,
  ICON_TABLE,
  ICON_TABS,
  ICON_TASK,
  ICON_THEME,
  ICON_TIMELINE,
  ICON_VIDEO,
  ICON_ATTR,
  ICON_CODE,
  ICON_CODEBLOCK,
  ICON_COMMENT,
  ICON_HIGHLIGHT,
  ICON_ITALIC,
  ICON_SPOILER,
  ICON_STRIKE,
  ICON_SUB,
  ICON_SUP,
} from "@/editor/toolbar/icons";
import { buildThemeMenuItems } from "@/editor/toolbar/themeItems";
import type { ToolbarItem } from "@/editor/toolbar/ToolbarItem";

export const DEFAULT_TOOLBAR_ITEMS: ToolbarItem[] = [
  {
    id: "textFormat",
    type: "menu",
    label: "格式",
    title: "行内格式",
    icon: ICON_BOLD,
    children: [
      { id: "bold", label: "加粗", title: "加粗", command: "bold" },
      { id: "italic", label: "斜体", title: "斜体", command: "italic" },
      {
        id: "strikethrough",
        label: "删除线",
        title: "删除线",
        command: "strikethrough",
      },
      { id: "code", label: "行内代码", title: "行内代码", command: "code" },
      { id: "formatSep1", type: "separator" },
      {
        id: "highlightMenu",
        type: "menu",
        label: "高亮",
        title: "高亮颜色选择",
        icon: ICON_HIGHLIGHT,
        children: [
          {
            id: "highlight",
            label: "默认",
            title: "==默认==",
            command: "highlight",
          },
          {
            id: "highlightNote",
            label: "说明 (Note)",
            title: "==说明=={.note}",
            command: "highlightNote",
          },
          {
            id: "highlightTip",
            label: "提示 (Tip)",
            title: "==提示=={.tip}",
            command: "highlightTip",
          },
          {
            id: "highlightImportant",
            label: "重要 (Important)",
            title: "==重要=={.important}",
            command: "highlightImportant",
          },
          {
            id: "highlightWarning",
            label: "警告 (Warning)",
            title: "==警告=={.warning}",
            command: "highlightWarning",
          },
          {
            id: "highlightCaution",
            label: "谨慎 (Caution)",
            title: "==谨慎=={.caution}",
            command: "highlightCaution",
          },
          {
            id: "highlightDanger",
            label: "危险 (Danger)",
            title: "==危险=={.danger}",
            command: "highlightDanger",
          },
        ],
      },
      { id: "spoiler", label: "剧透", title: "!!剧透!!", command: "spoiler" },
      { id: "sup", label: "上标", title: "^上标^", command: "sup" },
      { id: "sub", label: "下标", title: "~下标~", command: "sub" },
      {
        id: "comment",
        label: "注释",
        title: "%%注释%%（跨行按行拆分）",
        command: "comment",
      },
      { id: "math", label: "行内公式", title: "$行内公式$", command: "math" },
    ],
  },
  {
    id: "structure",
    type: "menu",
    label: "结构",
    title: "标题 / 列表 / 引用",
    icon: ICON_STRUCTURE,
    children: [
      {
        id: "heading",
        type: "menu",
        label: "标题",
        title: "ATX 标题",
        icon: ICON_HEADING,
        children: [
          { id: "heading1", label: "一级标题", command: "heading1" },
          { id: "heading2", label: "二级标题", command: "heading2" },
          { id: "heading3", label: "三级标题", command: "heading3" },
          { id: "heading4", label: "四级标题", command: "heading4" },
          { id: "heading5", label: "五级标题", command: "heading5" },
          { id: "heading6", label: "六级标题", command: "heading6" },
        ],
      },
      { id: "unorderedList", label: "无序列表", command: "unorderedList" },
      { id: "orderedList", label: "有序列表", command: "orderedList" },
      {
        id: "taskListMenu",
        type: "menu",
        label: "任务列表",
        icon: ICON_TASK,
        children: [
          { id: "taskList", label: "待办", command: "taskList" },
          { id: "taskInProgress", label: "进行中", command: "taskInProgress" },
          { id: "taskDeferred", label: "延期", command: "taskDeferred" },
          { id: "taskEarly", label: "提前", command: "taskEarly" },
          { id: "taskCancelled", label: "取消", command: "taskCancelled" },
          { id: "taskUrgent", label: "紧急", command: "taskUrgent" },
          { id: "taskDone", label: "已完成", command: "taskDone" },
        ],
      },
      { id: "blockquote", label: "引用", command: "blockquote" },
      {
        id: "codeBlockMenu",
        type: "menu",
        label: "代码块",
        icon: ICON_CODEBLOCK,
        children: [
          {
            id: "codeBlockBasic",
            label: "基础围栏",
            command: "codeBlockBasic",
          },
          {
            id: "codeBlockTitle",
            label: "带文件名",
            command: "codeBlockTitle",
          },
          {
            id: "codeBlockHighlight",
            label: "行号高亮",
            command: "codeBlockHighlight",
          },
          {
            id: "codeBlockCollapse",
            label: "折叠长代码",
            command: "codeBlockCollapse",
          },
        ],
      },
      { id: "horizontalRule", label: "分隔线", command: "horizontalRule" },
    ],
  },
  {
    id: "insert",
    type: "menu",
    label: "插入",
    title: "链接 / 媒体",
    icon: ICON_PLUS,
    children: [
      { id: "link", label: "链接", command: "link" },
      {
        id: "linkRefMenu",
        type: "menu",
        label: "链接引用",
        icon: ICON_LINK,
        children: [
          {
            id: "linkReference",
            label: "引用式链接",
            title: "[文本][标识]",
            command: "linkReference",
          },
          {
            id: "linkRefDef",
            label: "链接引用定义",
            title: "[标识]: url",
            command: "linkRefDef",
          },
        ],
      },
      { id: "image", label: "图片", command: "image" },
      { id: "table", label: "表格", command: "table" },
      {
        id: "media",
        type: "menu",
        label: "媒体",
        icon: ICON_VIDEO,
        children: [
          { id: "video", label: "视频", command: "video" },
          { id: "audio", label: "音频", command: "audio" },
          { id: "iframe", label: "嵌入页", command: "iframe" },
        ],
      },
      { id: "insertSep1", type: "separator" },
      { id: "emoji", label: "Emoji", command: "emoji" },
      { id: "badge", label: "徽章", command: "badge" },
      {
        id: "footnoteMenu",
        type: "menu",
        label: "脚注",
        icon: ICON_FOOTNOTE,
        children: [
          { id: "footnoteRef", label: "插入引用", command: "footnoteRef" },
          { id: "footnoteDef", label: "插入定义", command: "footnoteDef" },
          { id: "footnoteBoth", label: "引用 + 定义", command: "footnoteBoth" },
        ],
      },
    ],
  },
  {
    id: "components",
    type: "menu",
    label: "组件",
    title: "扩展 UI 区块",
    icon: ICON_BLOCKS,
    mobileOverflow: true,
    children: [
      {
        id: "alertMenu",
        type: "menu",
        label: "GitHub 告警",
        icon: ICON_ALERT,
        children: [
          { id: "alertNote", label: "说明", command: "alertNote" },
          { id: "alertTip", label: "提示", command: "alertTip" },
          {
            id: "alertImportant",
            label: "重要",
            command: "alertImportant",
          },
          {
            id: "alertWarning",
            label: "警告",
            command: "alertWarning",
          },
          {
            id: "alertCaution",
            label: "谨慎",
            command: "alertCaution",
          },
        ],
      },
      {
        id: "containerMenu",
        type: "menu",
        label: "自定义容器",
        icon: ICON_CONTAINER,
        children: [
          { id: "containerTip", label: "提示", command: "containerTip" },
          {
            id: "containerWarning",
            label: "警告",
            command: "containerWarning",
          },
          { id: "containerNote", label: "说明", command: "containerNote" },
          { id: "containerInfo", label: "信息", command: "containerInfo" },
          {
            id: "containerImportant",
            label: "重要",
            command: "containerImportant",
          },
          {
            id: "containerCaution",
            label: "谨慎",
            command: "containerCaution",
          },
          { id: "containerDanger", label: "危险", command: "containerDanger" },
          { id: "containerCenter", label: "居中", command: "containerCenter" },
          { id: "containerLeft", label: "左对齐", command: "containerLeft" },
          { id: "containerRight", label: "右对齐", command: "containerRight" },
          {
            id: "containerJustify",
            label: "两端对齐",
            command: "containerJustify",
          },
        ],
      },
      { id: "componentsSep1", type: "separator" },
      {
        id: "collapseMenu",
        type: "menu",
        label: "折叠面板",
        icon: ICON_COLLAPSE,
        children: [
          {
            id: "collapseDefault",
            label: "手风琴（默认折叠）",
            command: "collapseDefault",
            icon: ICON_COLLAPSE,
          },
          {
            id: "collapseExpanded",
            label: "手风琴（默认展开）",
            command: "collapseExpanded",
            icon: ICON_COLLAPSE,
          },
          {
            id: "collapseExpand",
            label: "多面板展开",
            title: "::: collapse expand",
            command: "collapseExpand",
            icon: ICON_COLLAPSE,
          },
        ],
      },
      { id: "tabs", label: "选项卡", command: "tabs" },
      { id: "steps", label: "步骤条", command: "steps" },
      {
        id: "timelineMenu",
        type: "menu",
        label: "时间线",
        icon: ICON_TIMELINE,
        children: [
          {
            id: "timelineContainer",
            label: "插入时间线容器",
            command: "timelineContainer",
            icon: ICON_TIMELINE,
          },
          {
            id: "timelineNode",
            label: "插入时间线",
            command: "timelineNode",
            icon: ICON_TIMELINE,
          },
        ],
      },
      { id: "componentsSep2", type: "separator" },
      {
        id: "cards",
        type: "menu",
        label: "卡片",
        icon: ICON_CARD,
        children: [
          { id: "card", label: "基础卡片", command: "card" },
          { id: "linkCard", label: "链接卡片", command: "linkCard" },
          { id: "imageCard", label: "图片卡片", command: "imageCard" },
          { id: "repoCard", label: "仓库卡片", command: "repoCard" },
          { id: "cardGrid", label: "卡片网格", command: "cardGrid" },
          { id: "cardMasonry", label: "瀑布流", command: "cardMasonry" },
        ],
      },
      {
        id: "fields",
        type: "menu",
        label: "字段",
        icon: ICON_FIELD,
        children: [
          { id: "field", label: "单个字段", command: "field" },
          { id: "fieldGroup", label: "字段组", command: "fieldGroup" },
        ],
      },
    ],
  },
  {
    id: "advanced",
    type: "menu",
    label: "高级",
    title: "图表与元数据",
    icon: ICON_EXT,
    mobileOverflow: true,
    children: [
      {
        id: "htmlAttr",
        label: "属性",
        title: "在选区后追加 {.class}",
        command: "htmlAttr",
      },
      { id: "mathBlock", label: "块级公式", command: "mathBlock" },
      { id: "commentBlock", label: "块级注释", command: "commentBlock" },
      {
        id: "mermaid",
        label: "Mermaid",
        title: "插入 Mermaid 图表",
        icon: ICON_MERMAID,
        command: "mermaid",
      },
      {
        id: "echarts",
        label: "ECharts",
        title: "插入 ECharts 图表",
        icon: ICON_ECHARTS,
        command: "echarts",
      },
      {
        id: "frontmatterMenu",
        type: "menu",
        label: "文档头",
        title: "YAML Frontmatter / 变量引用",
        icon: ICON_FRONTMATTER,
        children: [
          {
            id: "frontmatter",
            label: "YAML 文档头",
            title: "---\\ntitle: ...\\n---",
            command: "frontmatter",
          },
          {
            id: "frontmatterVar",
            label: "变量引用",
            title: "[[变量名]]",
            command: "frontmatterVar",
          },
        ],
      },
    ],
  },
  {
    id: "themeMenu",
    type: "menu",
    label: "主题",
    title: "切换渲染主题",
    icon: ICON_THEME,
    mobileOverflow: true,
    children: buildThemeMenuItems(),
  },
];
